#Local environment and project settings
spring.application.name=officespace
server.port=${SERVER_PORT:8080}

#server.servlet.context-path=/api

# Database configuration
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/officespace
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Optional: Spring Boot auto-detects this, but if you want it explicit:
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#JWT Settings
security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY:default-secret-key-that-is-at-least-thirty-two-bytes-long}
security.jwt.expiration-time=${SECURITY_JWT_EXPIRATION_TIME:86400000}
security.jwt.refresh-token-expiration-time=${SECURITY_REFRESH_JWT_EXPIRATION_TIME:604800000}

#Logging configuration
logging.level.root = INFO

logging.file.name=logs/application.log
logging.file.path=logs

# Logging patterns and levels
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Rolling file configuration
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=100MB

logging.logback.rollingpolicy.clean-history-on-start=true

spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:dummy@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:password}
spring.mail.transport.protocol=${SPRING_MAIL_TRANSPORT_PROTOCOL:smtp}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.starttls.required=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED:true}
spring.mail.properties.mail.debug=${SPRING_MAIL_DEBUG:false}

spring.config.import=optional:classpath:application-secrets.properties

# Google Calendar API Configuration
google.calendar.application-name=${GOOGLE_CALENDAR_APPLICATION_NAME:OfficeSpace}
google.calendar.tokens-directory-path=${GOOGLE_CALENDAR_TOKENS_DIRECTORY_PATH:tokens}
google.calendar.credentials-directory-path=${GOOGLE_CALENDAR_CREDENTIALS_DIRECTORY_PATH:src/main/resources}
google.calendar.client-id=${GOOGLE_CALENDAR_CLIENT_ID}
google.calendar.client-secret=${GOOGLE_CALENDAR_CLIENT_SECRET}
google.calendar.redirect-uri=${GOOGLE_CALENDAR_REDIRECT_URI:http://localhost:8888/callback}